version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: mydb

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: migrate-mongo
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
    command: npm run migrate:up
    restart: "no"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-api
    depends_on:
      - mongo
      - migrate
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
    command: npm start
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  mongo-data:
